"""rename metadata to event_metadata in analytics_events

Revision ID: 8127cae6832c
Revises: 001
Create Date: 2026-04-22 20:07:10.298544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8127cae6832c'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_events', sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('analytics_events', 'metadata')
    op.drop_index('idx_installations_status', table_name='installations')
    op.drop_index('idx_leads_staff', table_name='leads')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_orders_customer', table_name='orders')
    op.add_column('products', sa.Column('sku', sa.String(), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Numeric(precision=10, scale=0), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('products', 'capacity_kw',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_index('idx_quotes_lead', table_name='quotes')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_index('idx_quotes_lead', 'quotes', ['lead_id'], unique=False)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.alter_column('products', 'capacity_kw',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'sku')
    op.create_index('idx_orders_customer', 'orders', ['customer_id'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_index('idx_leads_staff', 'leads', ['assigned_staff_id'], unique=False)
    op.create_index('idx_installations_status', 'installations', ['status'], unique=False)
    op.add_column('analytics_events', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('analytics_events', 'event_metadata')
    # ### end Alembic commands ###
