"""add location fields to installations

Revision ID: 806a6dd38b15
Revises: 60b209f12ef4
Create Date: 2026-04-22 20:22:34.549893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806a6dd38b15'
down_revision = '60b209f12ef4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installations', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('installations', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('installations', sa.Column('site_address', sa.String(), nullable=True))
    op.add_column('installations', sa.Column('city', sa.String(), nullable=True))
    op.add_column('installations', sa.Column('state', sa.String(), nullable=True))
    op.add_column('installations', sa.Column('country', sa.String(), nullable=True))
    op.add_column('installations', sa.Column('postal_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installations', 'postal_code')
    op.drop_column('installations', 'country')
    op.drop_column('installations', 'state')
    op.drop_column('installations', 'city')
    op.drop_column('installations', 'site_address')
    op.drop_column('installations', 'longitude')
    op.drop_column('installations', 'latitude')
    # ### end Alembic commands ###
