"""add location fields to users

Revision ID: 60b209f12ef4
Revises: 8127cae6832c
Create Date: 2026-04-22 20:13:41.063956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b209f12ef4'
down_revision = '8127cae6832c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location_sharing_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location_sharing_enabled')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'country')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    # ### end Alembic commands ###
